In [2]:
#full course on Pandas


import pandas as pd
s1=pd.Series(10)
print(s1) 
print("over here s1 is a series object and in the output 0 is the index number ad=nd 10 is the content in that index")
print(".")
print(".")
print(".")


print("creating a second series object")
s2=pd.Series([10,9,8,7])

print(s2)
print("over here we are giving a number of values, the values are stored in a column wise order with the respective indexes")
print(".")
print(".")
print(".")



print("to add costum index")

s3=pd.Series([2,3,4],index=[10,2,6])
print(s3)
print(".")
print(".")

0    10
dtype: int64
over here s1 is a series object and in the output 0 is the index number ad=nd 10 is the content in that index
.
.
.
creating a second series object
0    10
1     9
2     8
3     7
dtype: int64
over here we are giving a number of values, the values are stored in a column wise order with the respective indexes
.
.
.
to add costum index
10    2
2     3
6     4
dtype: int64
.
.


In [3]:
import pandas as pd
import numpy as np


s1=pd.Series([100,200,300,np.nan,500,np.nan])
print(s1)
s1.fillna(-99,inplace=True) #or we could have s1.dropna(inplace= True) inplace= Ture enables us to edit. drop na means to remove na 
#                           fill na means inplace of nan replace -99
print(s1)

print("to print the length of a series")
print(len(s1))

print("the number of counts per value")

print(s1.value_counts()) #displays the values in descendig order



0    100.0
1    200.0
2    300.0
3      NaN
4    500.0
5      NaN
dtype: float64
0    100.0
1    200.0
2    300.0
3    -99.0
4    500.0
5    -99.0
dtype: float64
to print the length of a series
6
the number of counts per value
-99.0     2
 500.0    1
 300.0    1
 200.0    1
 100.0    1
dtype: int64


In [4]:
import pandas as pd
import numpy as np


s1=pd.Series([100,200,300,400,500,6000,np.nan],index=['sat','sun','mon','tue','wed','thurs','fri'])
print(s1)
index=s1.index
value=s1.values
print("the index is",index)
print("the value is",value)

sat       100.0
sun       200.0
mon       300.0
tue       400.0
wed       500.0
thurs    6000.0
fri         NaN
dtype: float64
the index is Index(['sat', 'sun', 'mon', 'tue', 'wed', 'thurs', 'fri'], dtype='object')
the value is [ 100.  200.  300.  400.  500. 6000.   nan]


In [5]:
#to view specific rows
print("printing the head value")
print(s1.head(2))
print("printing the tail value")
print(s1.tail(2))
print("to print or retrive a value")
print(s1['sun'])

printing the head value
sat    100.0
sun    200.0
dtype: float64
printing the tail value
thurs    6000.0
fri         NaN
dtype: float64
to print or retrive a value
200.0


In [6]:
import pandas as pd
import numpy as np
import quandl as qd
#the excample of workinng on summaoion of series



s1=pd.Series([1,2,3],index=['a','b','c'])
a2=pd.Series([2,1,3,4],index=['b','c','a','d'])
print(s1+a2)
print("the addition of tow series takes place in order of their indices ie. a is added to a, b is added to  b and so on and the sum is displayed in ascending order")
print("d is displayed as NaN as it is not common in both the series")

a    4.0
b    4.0
c    4.0
d    NaN
dtype: float64
the addition of tow series takes place in order of their indices ie. a is added to a, b is added to  b and so on and the sum is displayed in ascending order
d is displayed as NaN as it is not common in both the series


In [7]:
#to change the  default index or the given index
s1.index=['1','2','3']
print(s1)

1    1
2    2
3    3
dtype: int64


In [8]:
#reindex([]) is used to change index as well


#to convert index values form string to integer values


s1.index=s1.index.values.astype(int)
print(s1)

1    1
2    2
3    3
dtype: int64


In [9]:
#to delet a row

s1=pd.Series([1,2,3],index=['a','b','c'])
del(s1['a'])
print(s1)

b    2
c    3
dtype: int64


In [10]:
import pandas as pd
s1=pd.Series([2,3,4,5,6,7,8,9])
print(s1)
print(s1[1::5])
print(s1[1:5:])


0    2
1    3
2    4
3    5
4    6
5    7
6    8
7    9
dtype: int64
1    3
6    8
dtype: int64
1    3
2    4
3    5
4    6
dtype: int64


In [11]:
import pandas as pd
import numpy as np

sales=pd.Series(['100','200','300'], index=['fb','google','youtube'])
#VIMP the series is ocnverted to the data frame over here when 2017n nis added
df=pd.DataFrame({2017:sales})
print(df)
df=pd.DataFrame({2019:sales,2017:sales,2015:sales,2011:sales})
print(df)
df.shape

        2017
fb       100
google   200
youtube  300
        2019 2017 2015 2011
fb       100  100  100  100
google   200  200  200  200
youtube  300  300  300  300


(3, 4)

In [12]:
df.head(2)


2019 2017 2015 2011
fb      100  100  100  100
google  200  200  200  200

In [13]:
df[[2015]].head(1)

2015
fb  100

In [14]:
df.tail(2)

2019 2017 2015 2011
google   200  200  200  200
youtube  300  300  300  300

In [15]:
df[[2017]].tail(2)

2017
google   200
youtube  300

In [16]:
print(type(df[[2017]].tail(2)))
print("this is a dataframe object")
#the syntax determines wether the object is series or a data frame

<class 'pandas.core.frame.DataFrame'>
this is a dataframe object


In [17]:
print(type(df[2017].tail(2)))
print("this is a series object")

<class 'pandas.core.series.Series'>
this is a series object


In [18]:
df.columns=['a','b','c','d']
df

a    b    c    d
fb       100  100  100  100
google   200  200  200  200
youtube  300  300  300  300

In [19]:
df.a

fb         100
google     200
youtube    300
Name: a, dtype: object

In [20]:
df.columns.get_loc('a')

0

In [21]:
df.columns=['a','b','c','d']
df

a    b    c    d
fb       100  100  100  100
google   200  200  200  200
youtube  300  300  300  300

In [22]:
import pandas as pd
import numpy as np

sales1=pd.Series([100,200,900],index=['a','b','c'])
sales2=pd.Series([400,300,800],index=['a','b','c'])
sales3=pd.Series([100,500,200],index=['a','b','c'])

df=pd.DataFrame({2017:sales1,2018:sales2,2019:sales3})



df.columns=['q','w','e']


df

q    w    e
a  100  400  100
b  200  300  500
c  900  800  200

In [23]:
df.columns

Index(['q', 'w', 'e'], dtype='object')

In [24]:
#to get value of (q,b) works if the column is a charector
df[df.q>150]

q    w    e
b  200  300  500
c  900  800  200

In [25]:
df['q'].b    #to get value of (q,b) works if the column is a charector

200

In [1]:

df2

NameError: name 'df2' is not defined

In [38]:
df.iat[0,2] #this method works for both the cases

100

In [39]:
df2.iat[0,2] #this method works for both the cases

100

In [26]:
#df.loc[['a','b']]
df

q    w    e  lable
a  100  400  100  500.0
b  200  300  500  200.0
c  900  800  200    NaN

In [25]:
df['lable']=df['e'].shift(-1)

In [27]:
df

q    w    e  lable
a  100  400  100  500.0
b  200  300  500  200.0
c  900  800  200    NaN

In [2]:
import pandas as pd
import numpy as np

sales1=pd.Series([100,200,900],index=['a','b','c'])
sales2=pd.Series([400,300,800],index=['a','b','c'])
sales3=pd.Series([100,500,200],index=['a','b','c'])

df=pd.DataFrame({2017:sales1,2018:sales2,2019:sales3})



df.columns=['q','w','e']


df

q    w    e
a  100  400  100
b  200  300  500
c  900  800  200

In [3]:
df['lable']=df['e'].shift(-1)

In [4]:
df

q    w    e  lable
a  100  400  100  500.0
b  200  300  500  200.0
c  900  800  200    NaN

In [6]:
x=np.array(df.drop(['lable'],1))
x

array([[100, 400, 100],
       [200, 300, 500],
       [900, 800, 200]], dtype=int64)

In [7]:
x=x[:-1]
x

array([[100, 400, 100],
       [200, 300, 500]], dtype=int64)

In [8]:
x_l=x[-1:]
x

array([[100, 400, 100],
       [200, 300, 500]], dtype=int64)

In [10]:
from sklearn import preprocessing
x=preprocessing.scale(x)
x

C:\Users\Christopher Gomes\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


array([[-1.,  1., -1.],
       [ 1., -1.,  1.]])

In [17]:
y=np.array(df['lable'])


array([500., 200.])

In [18]:
y

array([500., 200.])

In [21]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
sales1=pd.Series([100,200,900],index=['a','b','c'])
sales2=pd.Series([400,300,800],index=['a','b','c'])
sales3=pd.Series([100,500,200],index=['a','b','c'])

df=pd.DataFrame({2017:sales1,2018:sales2,2019:sales3})



df.columns=['q','w','e']

df['lable']=df['e'].shift(-1)
df

q    w    e  lable
a  100  400  100  500.0
b  200  300  500  200.0
c  900  800  200    NaN

In [22]:
forecast_out=1
x=np.array(df.drop(['lable'],1))
x=x[:-forecast_out]
x_lately=x[-forecast_out:]
x=preprocessing.scale(x)

df.dropna(inplace=True)
y=np.array(df['lable'])


print("the length of x is",len(x))
print("the  length  of y is", len(y))


the length of x is 2
the  length  of y is 2


C:\Users\Christopher Gomes\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [ ]:
df2.at['b',2014]